import { useEffect, useState } from "react";
import { adminPurchaseApi, type AdminSettings, type AdminSource } from "@/lib/marketplace-purchase-api";
import { MarketplacePurchaseNav } from "@/components/marketplace-purchase-nav";
import { Card } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Button } from "@/components/ui/button";

export default function MarketplacePurchaseSettingsPage() {
  const [sources, setSources] = useState<AdminSource[]>([]); const [settings, setSettings] = useState<AdminSettings>({ serviceFeePercent: 10, shippingPerKgTmt: 0, minimumFeeTmt: 0, quoteTtlMinutes: 1440 }); const [error, setError] = useState("");
  const load = () => Promise.all([adminPurchaseApi.sources(), adminPurchaseApi.settings()]).then(([s, v]) => { setSources(s); setSettings(v); }).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, []);
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Cargo · Buy desk</p><h1 className="mt-1 text-2xl font-bold">Источники и правила выкупа</h1></header><MarketplacePurchaseNav/>{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}
    <Card className="p-5"><h2 className="font-bold">Маркетплейсы</h2><p className="mt-1 text-xs text-slate-400">Источники меняются через конфигурацию сервиса; здесь виден фактический активный контракт.</p><div className="mt-4 divide-y">{sources.map((source) => <div key={source.code} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-44 flex-1"><p className="font-semibold">{source.name}</p><p className="text-xs text-slate-400">{source.allowedHosts.join(", ")} · {source.adapterKey}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{source.requiresManualReview ? "Ручная проверка" : "Автопроверка"}</span><span className={source.isEnabled?"text-xs font-semibold text-emerald-700":"text-xs text-slate-400"}>{source.isEnabled?"Включён":"Выключен"}</span></div>)}</div></Card>
    <Card className="p-5"><h2 className="font-bold">Правила расчёта</h2><div className="mt-4 grid gap-4 sm:grid-cols-4"><label className="text-xs text-slate-500">Комиссия, %<Input type="number" value={settings.serviceFeePercent} onChange={(e) => setSettings({...settings, serviceFeePercent:Number(e.target.value)})}/></label><label className="text-xs text-slate-500">Доставка за кг, TMT<Input type="number" value={settings.shippingPerKgTmt} onChange={(e) => setSettings({...settings, shippingPerKgTmt:Number(e.target.value)})}/></label><label className="text-xs text-slate-500">Минимальная комиссия<Input type="number" value={settings.minimumFeeTmt} onChange={(e) => setSettings({...settings, minimumFeeTmt:Number(e.target.value)})}/></label><label className="text-xs text-slate-500">Срок котировки, мин<Input type="number" value={settings.quoteTtlMinutes} onChange={(e) => setSettings({...settings, quoteTtlMinutes:Number(e.target.value)})}/></label></div><Button className="mt-4" onClick={() => adminPurchaseApi.saveSettings(settings).then(setSettings).catch((e) => setError(e.message))}>Сохранить правила</Button></Card>
  </div>;
}
