"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { LinkSimple, Plus, Trash } from "@phosphor-icons/react/dist/ssr";
import { useTranslation } from "@topup-hub/i18n";
import { isAuthenticated } from "@/lib/api";
import { purchaseApi, type PurchaseItem, type PurchaseSource } from "@/lib/marketplace-purchase-api";
import { PurchaseRoute } from "@/components/cargo/purchase-route";
import { Card } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input";

export default function MarketplaceBuyPage(){const{t}=useTranslation();const router=useRouter();const[sources,setSources]=useState<PurchaseSource[]|null>(null);const[url,setUrl]=useState("");const[items,setItems]=useState<PurchaseItem[]>([]);const[address,setAddress]=useState("");const[currency,setCurrency]=useState("RUB");const[busy,setBusy]=useState(false);const[resolving,setResolving]=useState(false);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{purchaseApi.sources().then(setSources).catch(()=>setSources([]));},[]);
 // Resolution is the server's job: it validates the host, strips tracking parameters and reads
 // the article number out of the URL. Matching hosts here meant the two clients could disagree
 // about the same link, and neither could name the article at all.
 async function addLink(e:React.FormEvent){e.preventDefault();if(!url.trim())return;setResolving(true);setError(null);try{const preview=await purchaseApi.resolve(url.trim());if(!preview.isProductPage){setError(t("web.purchase.notAProduct"));return;}setItems(v=>{const at=v.findIndex(i=>i.canonicalUrl===preview.canonicalUrl);if(at===-1)return [...v,{sourceCode:preview.sourceCode,canonicalUrl:preview.canonicalUrl,url:preview.canonicalUrl,externalIdSnapshot:preview.externalId,quantity:1}];return v.map((i,n)=>n===at?{...i,quantity:Math.min(99,i.quantity+1)}:i);});setUrl("");}catch(err){setError(err instanceof Error?err.message:t("web.purchase.previewError"));}finally{setResolving(false);}}
 async function submit(){if(!items.length||address.trim().length<5)return;if(!isAuthenticated())return router.push("/login?next=/cargo/buy");setBusy(true);setError(null);const key=`web-buy-${crypto.randomUUID()}`;try{const order=await purchaseApi.create({items,currency,deliveryAddress:address.trim(),idempotencyKey:key},key);router.push(`/cargo/buy/orders/${order.id}`);}catch(e){setError(e instanceof Error?e.message:t("web.purchase.createError"));setBusy(false);}}
 return <main className="min-h-screen bg-[linear-gradient(180deg,#eef4ff_0%,#f8fafc_44%)] px-4 py-10 dark:bg-[linear-gradient(180deg,#111936_0%,#0b0b16_44%)]"><div className="mx-auto max-w-4xl space-y-8"><header className="space-y-4"><p className="text-xs font-bold uppercase tracking-[.22em] text-brand-600">{t("web.purchase.eyebrow")}</p><h1 className="max-w-2xl text-3xl font-black tracking-tight sm:text-5xl">{t("web.purchase.title")}</h1><p className="max-w-2xl text-slate-600 dark:text-slate-300">{t("web.purchase.subtitle")}</p><PurchaseRoute active={items.length?1:0}/></header>
 <Card className="p-5 sm:p-7"><form onSubmit={addLink} className="space-y-3"><label htmlFor="product-url" className="text-sm font-bold">{t("web.purchase.linkLabel")}</label><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><LinkSimple className="absolute left-3 top-3 text-slate-400"/><Input id="product-url" type="url" className="pl-10" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." required/></div><Button disabled={resolving||!url.trim()}><Plus/>{resolving?t("common.loading"):t("web.purchase.add")}</Button></div><p className="text-xs text-slate-400">{sources===null?t("common.loading"):sources.length?`${t("web.purchase.supported")}: ${sources.map(s=>s.name).join(", ")}`:t("web.purchase.sourcesEmpty")}</p></form></Card>
 {error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{!items.length?<div className="rounded-3xl border border-dashed border-slate-300 px-6 py-12 text-center text-sm text-slate-500">{t("web.purchase.cartEmpty")}</div>:<div className="grid gap-6 lg:grid-cols-[1fr_280px]"><section className="space-y-3"><h2 className="text-xl font-black">{t("web.purchase.cartTitle")}</h2>{items.map((item,i)=><Card key={`${item.url}-${i}`} className="p-4"><div className="flex gap-3"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xs text-slate-400">URL</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.sourceCode}{item.externalIdSnapshot?` · ${item.externalIdSnapshot}`:""}</p><p className="truncate text-xs text-slate-400">{item.canonicalUrl??item.url}</p><p className="mt-1 text-xs text-amber-700">{t("web.purchase.manualReview")}</p><div className="mt-3 flex gap-2"><Input aria-label={t("web.purchase.variant")} placeholder={t("web.purchase.variant")} value={item.variant??""} onChange={e=>setItems(a=>a.map((v,n)=>n===i?{...v,variant:e.target.value}:v))} className="h-9 max-w-52"/><Input aria-label={t("web.purchase.quantity")} type="number" min={1} max={99} value={item.quantity} onChange={e=>setItems(a=>a.map((v,n)=>n===i?{...v,quantity:Math.max(1,Number(e.target.value))}:v))} className="h-9 w-20"/></div></div><button aria-label={t("web.purchase.remove")} onClick={()=>setItems(a=>a.filter((_,n)=>n!==i))} className="h-9 rounded-lg p-2 text-slate-400 hover:text-rose-600"><Trash/></button></div></Card>)}<Card className="space-y-3 p-5"><label className="text-sm font-bold" htmlFor="address">{t("web.purchase.address")}</label><Input id="address" value={address} onChange={e=>setAddress(e.target.value)} required/><label className="text-sm font-bold" htmlFor="currency">{t("web.cargo.currency")}</label><select id="currency" value={currency} onChange={e=>setCurrency(e.target.value)} className="h-10 w-full rounded-xl border bg-white px-3"><option>RUB</option><option>USD</option><option>TRY</option><option>CNY</option></select></Card></section>
 <aside className="lg:sticky lg:top-24 lg:h-fit"><Card className="overflow-hidden border-slate-900 p-0"><div className="bg-slate-950 p-5 text-white"><p className="text-xs uppercase tracking-widest text-slate-400">{t("web.purchase.costRail")}</p><p className="mt-3 text-xl font-black">{t("web.purchase.manualReview")}</p></div><div className="space-y-4 p-5"><p className="text-sm text-slate-600">{t("web.purchase.quoteAfterReview")}</p><Button className="w-full" onClick={submit} disabled={busy||address.trim().length<5}>{busy?t("common.loading"):t("web.purchase.sendReview")}</Button></div></Card></aside></div>}</div></main>;
}
