// Generates docs/analysis/FACTS.md: every countable fact about the repository, computed from the
// tracked files instead of typed by hand, so the numbers in the documentation cannot drift.
//
//   node scripts/docs-facts.mjs          rewrite docs/analysis/FACTS.md
//   node scripts/docs-facts.mjs --check  exit 1 when the file is out of date (used by CI)
//
// Deterministic on purpose: no dates, no commit hashes, no machine-dependent values. Two runs on the
// same tree give the same bytes, which is what makes --check meaningful.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const target = join(root, "docs", "analysis", "FACTS.md");

const tracked = execFileSync("git", ["ls-files"], { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 })
  .split("\n")
  .filter(Boolean);

const read = (file) => readFileSync(join(root, file), "utf8");
const lines = (file) => read(file).split("\n").length;
const isTest = (f) => /(\.spec\.|\.test\.|_test\.dart$)/.test(f) || /(^|\/)test\//.test(f);
const under = (prefix) => tracked.filter((f) => f.startsWith(prefix));
const count = (list, re) => list.filter((f) => re.test(f)).length;

function loc(prefix, extRe) {
  const files = under(prefix).filter((f) => extRe.test(f));
  let src = 0;
  let tests = 0;
  for (const f of files) (isTest(f) ? (tests += lines(f)) : (src += lines(f)));
  return { src, tests, files: files.length };
}

const rows = [];
const table = (head, body) => {
  rows.push(`| ${head.join(" | ")} |`, `| ${head.map(() => "---").join(" | ")} |`);
  for (const r of body) rows.push(`| ${r.join(" | ")} |`);
  rows.push("");
};
const h = (t) => rows.push(`## ${t}`, "");
const p = (t) => rows.push(t, "");

rows.push(
  "# Facts (generated)",
  "",
  "> **Do not edit by hand.** Generated by `node scripts/docs-facts.mjs` (`pnpm docs:facts`); CI runs",
  "> `pnpm docs:check` and fails when this file is stale. Regenerate it in the same PR as the change that",
  "> moved a number. Interpretation of these numbers lives in the other documents of this folder.",
  "",
);

// ---- Code size ----
h("Code size");
const areas = [
  ["API (NestJS)", "apps/api/src/", /\.ts$/],
  ["Web (Next.js)", "apps/web/src/", /\.tsx?$/],
  ["Admin (Vite)", "apps/admin/src/", /\.tsx?$/],
  ["Mobile (Flutter)", "apps/mobile/lib/", /\.dart$/],
  ["packages/types", "packages/types/src/", /\.ts$/],
  ["packages/api-client", "packages/api-client/src/", /\.ts$/],
  ["packages/i18n", "packages/i18n/src/", /\.ts$/],
];
table(
  ["Area", "Source lines", "Files"],
  areas.map(([name, prefix, re]) => {
    const r = loc(prefix, re);
    return [name, String(r.src), String(r.files)];
  }),
);

h("Automated tests");
const apiSpecs = count(tracked, /^apps\/api\/.*\.spec\.ts$/);
const mobileTests = count(tracked, /^apps\/mobile\/test\/.*_test\.dart$/);
const webAdminTests = count(tracked, /^apps\/(web|admin)\/.*\.(test|spec)\.tsx?$/);
const pkgTests = count(tracked, /^packages\/.*\.(test|spec)\.tsx?$/);
table(
  ["Where", "Test files", "Test lines"],
  [
    ["API (jest)", String(apiSpecs), String(loc("apps/api/", /\.spec\.ts$/).tests)],
    ["Mobile (flutter test)", String(mobileTests), String(loc("apps/mobile/test/", /_test\.dart$/).tests)],
    ["Web + Admin", String(webAdminTests), "0"],
    ["packages/*", String(pkgTests), "0"],
  ],
);

// ---- API ----
h("API");
const apiSrc = under("apps/api/src/");
const modules = [...new Set(apiSrc.map((f) => f.split("/")[3]).filter((x) => x && !x.includes(".")))].sort();
const controllers = apiSrc.filter((f) => f.endsWith(".controller.ts"));
const routeRe = /@(Get|Post|Put|Patch|Delete)\(/g;
let routes = 0;
let adminRoutes = 0;
for (const f of controllers) {
  const src = read(f);
  const n = (src.match(routeRe) ?? []).length;
  routes += n;
  if (/@Controller\(\s*["'`]admin\//.test(src)) adminRoutes += n;
}
table(
  ["Metric", "Value"],
  [
    ["Feature modules (directories under apps/api/src)", String(modules.length)],
    ["Controllers", String(controllers.length)],
    ["HTTP route handlers", String(routes)],
    ["  of which under /admin/*", String(adminRoutes)],
  ],
);
p(`Modules: ${modules.join(", ")}.`);

// ---- Database ----
h("Database (Prisma)");
const schema = read("apps/api/prisma/schema.prisma");
const migrations = tracked.filter((f) => /^apps\/api\/prisma\/migrations\/[^/]+\/migration\.sql$/.test(f));
const destructive = migrations.filter((f) => /migration-policy:\s*allow-destructive/i.test(read(f)));
table(
  ["Metric", "Value"],
  [
    ["Models", String((schema.match(/^model /gm) ?? []).length)],
    ["Enums", String((schema.match(/^enum /gm) ?? []).length)],
    ["Migrations", String(migrations.length)],
    ["Migrations carrying allow-destructive", String(destructive.length)],
  ],
);

// ---- Clients ----
h("Clients");
const features = [...new Set(under("apps/mobile/lib/features/").map((f) => f.split("/")[4]))].sort();
table(
  ["Mobile feature", "Screens", "Test files"],
  features.map((name) => [
    name,
    String(count(under(`apps/mobile/lib/features/${name}/`), /_screen\.dart$/)),
    String(count(under(`apps/mobile/test/features/${name}/`), /_test\.dart$/)),
  ]),
);
const webRoutes = tracked.filter((f) => /^apps\/web\/src\/app\/.*page\.tsx$/.test(f)).length;
const adminPages = tracked.filter((f) => /^apps\/admin\/src\/pages\/.*\.tsx$/.test(f)).length;
table(
  ["Client", "Value"],
  [
    ["Web pages (Next.js app router)", String(webRoutes)],
    ["Admin pages", String(adminPages)],
    ["Mobile locales", "ru, en, tkm"],
  ],
);

// ---- Infrastructure ----
h("Infrastructure as code");
const workflows = tracked.filter((f) => /^\.github\/workflows\/[^/]+\.ya?ml$/.test(f)).map((f) => f.split("/").pop());
const scheduled = workflows.filter((f) => /^\s*schedule:/m.test(read(`.github/workflows/${f}`)));
table(
  ["Metric", "Value"],
  [
    ["GitHub Actions workflows", String(workflows.length)],
    ["  of which run on a schedule", String(scheduled.length)],
    ["nginx vhosts (infra/nginx)", String(count(tracked, /^infra\/nginx\/.*\.conf$/))],
    ["Docker compose files", String(count(tracked, /^docker-compose.*\.ya?ml$/))],
  ],
);
p(`Workflows: ${workflows.join(", ")}.`);
p(`Scheduled: ${scheduled.join(", ")}.`);

// ---- Dependencies ----
h("Direct dependencies");
const pkgs = tracked.filter((f) => /^(apps|packages)\/[^/]+\/package\.json$/.test(f)).sort();
table(
  ["Package", "dependencies", "devDependencies"],
  pkgs.map((f) => {
    const j = JSON.parse(read(f));
    return [j.name ?? f, String(Object.keys(j.dependencies ?? {}).length), String(Object.keys(j.devDependencies ?? {}).length)];
  }),
);
const pub = read("apps/mobile/pubspec.yaml");
const pubDeps = pub.split(/^dev_dependencies:/m)[0].split(/^dependencies:/m)[1] ?? "";
p(`Mobile (pubspec) direct dependencies: ${(pubDeps.match(/^ {2}[a-z_0-9]+:/gm) ?? []).length}. App version: ${(pub.match(/^version:\s*(\S+)/m) ?? [])[1]}.`);

// ---- Documentation ----
h("Documentation");
const docs = tracked.filter((f) => /^docs\/.*\.md$/.test(f));
p(`Markdown documents under docs/: ${docs.length}.`);

const out = rows.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== out) {
    console.error("docs/analysis/FACTS.md is out of date. Run `pnpm docs:facts` and commit the result.");
    process.exit(1);
  }
  console.log("docs/analysis/FACTS.md is up to date.");
} else {
  writeFileSync(target, out);
  console.log(`Wrote ${target.replace(root, "")}`);
}
