name: tmp mail log
on:
  workflow_dispatch:
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SECONDARY_HOST }} >> ~/.ssh/known_hosts
      - name: Mail log
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SECONDARY_USER }}@${{ secrets.SECONDARY_HOST }} '
            docker run --rm --pid=host --privileged -v /:/host alpine chroot /host /bin/sh -c "journalctl -u postfix@- -u postfix --since \"5 minutes ago\" --no-pager | grep -E \"status=|reject|warning: [^s]|error\" | tail -10"
          ' < /dev/null
